/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Availability_read"];
        put: operations["Availability_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Bookings_list"];
        put?: never;
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventTypes_list"];
        put?: never;
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete: operations["EventTypes_remove"];
        options?: never;
        head?: never;
        patch: operations["EventTypes_update"];
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AvailabilityInterval: {
            weekday: components["schemas"]["Weekday"];
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
        };
        AvailabilitySchedule: {
            timeZone: string;
            intervals: components["schemas"]["AvailabilityInterval"][];
        };
        Booking: {
            readonly id: string;
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            readonly end: string;
            guestName: string;
            guestEmail: components["schemas"]["Email"];
            notes?: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        BookingCreate: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            start: string;
            guestName: string;
            guestEmail: components["schemas"]["Email"];
            notes?: string;
        };
        BookingListItem: {
            readonly id: string;
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            readonly end: string;
            guestName: string;
            guestEmail: components["schemas"]["Email"];
            notes?: string;
            /** Format: date-time */
            readonly createdAt: string;
            eventTypeTitle: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        DaySlots: {
            /** Format: date */
            date: string;
            slots: components["schemas"]["Slot"][];
        };
        /** Format: email */
        Email: string;
        EventType: {
            readonly id: components["schemas"]["EventTypeId"];
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        EventTypeCreate: {
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** Format: uuid */
        EventTypeId: string;
        EventTypeUpdate: {
            title?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        Slot: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            available: boolean;
        };
        SlotNotAlignedError: {
            /** @enum {string} */
            code: "SLOT_NOT_ALIGNED";
            message: string;
        };
        SlotOutOfRangeError: {
            /** @enum {string} */
            code: "SLOT_OUT_OF_RANGE";
            message: string;
        };
        SlotTakenError: {
            /** @enum {string} */
            code: "SLOT_TAKEN";
            message: string;
        };
        SlotsResponse: {
            eventTypeId: components["schemas"]["EventTypeId"];
            /** Format: int32 */
            durationMinutes: number;
            timeZone: string;
            /** Format: date */
            rangeStart: string;
            /** Format: date */
            rangeEnd: string;
            days: components["schemas"]["DaySlots"][];
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
            details: components["schemas"]["ValidationErrorDetail"][];
        };
        ValidationErrorDetail: {
            field: string;
            message: string;
        };
        /** @enum {string} */
        Weekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Availability_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySchedule"];
                };
            };
        };
    };
    Availability_replace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilitySchedule"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySchedule"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    Bookings_list: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                upcoming?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListItem"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"] | components["schemas"]["SlotOutOfRangeError"] | components["schemas"]["SlotNotAlignedError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotTakenError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: components["schemas"]["EventTypeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
